### ISSUE TITLE
Proposed msg changes

### ISSUE THREAD

**Issue by ichumuh** [SemRoCo/giskard_msgs#6]
While implementing the new interface I came up with some idea on how to improve the msgs:
Move.action
- add time_out parameter

Controller.msg
- rename threshold_value -> max_speed, as it is easier to interpret. m/s for translation, rad/s for rotation. It would also be a low hanging fruit to overwrite the joint speed, if the new one is smaller than the old one.
- remove enable_error_threshold, because we don't need it if we have max_speed
- replace goal_state with name+position, not sure about this. It would make it easier to set different weights and stuff for different joints. But it would make it more annoying to send a goal for all joints.

CollisionEntry.msg
- min_dist, its in the expression anyway
- max_dist? it also in the expression, might open up some interesting possibilities 
- ALLOW_ALL_COLLISION=2
- AVOID_ALL_COLLISION=3

**Comment by airballking** [comment]
Cool ideas! More detailed feedback:

> Move.action
> - add time_out 

Is this how long the actual planning shall take in real time? Or is this the maximum length of a planned trajectory?

> Controller.msg
> - rename threshold_value -> max_speed, as it is easier to interpret. m/s for translation, rad/s for rotation. It would also be a low hanging fruit to overwrite the joint speed, if the new one is smaller than the old one.
> - remove enable_error_threshold, because we don't need it if we have max_speed

I like this idea, it clarifies the interface. However, this will be a breaking change for giskard_ros. So, I suggest putting this into a standalone pull request.

> - replace goal_state with name+position, not sure about this. It would make it easier to set different weights and stuff for different joints. But it would make it more annoying to send a goal for all joints.

I did not understand this suggestion. Could you please provide an example?

> CollisionEntry.msg
> - min_dist, its in the expression anyway

Good idea. Feel free to extend the interface through a direct push to master, if you want.

> - max_dist? it also in the expression, might open up some interesting possibilities

Could be fun. Do you intend to use this as a constraint that is enforced during the motion or only as a parameter to stop collision checking early?

> - ALLOW_ALL_COLLISION=2
> - AVOID_ALL_COLLISION=3

This relates to body A, correct?

**Comment by ichumuh** [comment]
> Is this how long the actual planning shall take in real time? Or is this the maximum length of a planned trajectory?

The maximum length of the planned trajectory. 

> I like this idea, it clarifies the interface. However, this will be a breaking change for giskard_ros. So, I suggest putting this into a standalone pull request.

Ok I'll do that.

> I did not understand this suggestion. Could you please provide an example?

I should have written "name+position for only a single joint". So instead of 1 controller with a joint state, you'd have a different controller for each joint. But I think I've just convinced myself that we should keep goal_state. My suggested change is probably annoying more often than not.

> Could be fun. Do you intend to use this as a constraint that is enforced during the motion or only as a parameter to stop collision checking early?

The first. min_dist is lbA and max_dist is ubA of the soft constraint. Currently max_dist is fixed at 1e9.

> This relates to body A, correct?

Yes
